### ISSUE TITLE
Fails to build on readthedocs

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zopetoolkit#33]
See https://readthedocs.org/projects/zopetoolkit/builds/7895159/.

**Comment by mgedmin** [comment]
```
Running Sphinx v1.7.9
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopetoolkit/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopetoolkit/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopetoolkit/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopetoolkit/envs/latest/local/lib/python2.7/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension ztksphinx (exception: cannot import name Directive)

Extension error:
Could not import extension ztksphinx (exception: cannot import name Directive)
```

**Comment by icemac** [comment]
Locally I was able to create the documentation by reproducing the steps done by RTD. That's strange.

**Comment by icemac** [comment]
@tseaver Could you please add me (`icemac`) as developer to https://readthedocs.org/projects/zopetoolkit/ to further investigate the problem?

**Comment by tseaver** [comment]
@icemac Done.

**Comment by icemac** [comment]
Thank you. Switching to Python 3 on RTD fixed the issue.
